# Generated by Django 5.2.11 on 2026-03-06 17:18

import A4.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fname',
            field=models.CharField(max_length=50, validators=[A4.validate.validate_name]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lname',
            field=models.CharField(max_length=50, validators=[A4.validate.validate_name]),
        ),
    ]
