# Generated by Django 5.2.11 on 2026-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A4', '0005_employee_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
