# Generated by Django 5.2.11 on 2026-03-06 17:20

import A4.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A4', '0002_remove_employee_id_alter_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=100, validators=[A4.validate.validate_email]),
        ),
    ]
